services:
  - type: web
    name: ecotrack-app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DATABASE_URL
        fromDatabase:
          name: ecotrack-db
          property: connectionString

databases:
  - name: ecotrack-db
    plan: free
    databaseName: ecotrack
    user: ecotrack  <-- CAMBIO AQUÃ